server:
  port: 8085

spring:
  application:
    name: insight-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:stockpulse}:${MONGO_PASSWORD:changeme}@localhost:27017/stockpulse?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: insight-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    com.stockpulse: DEBUG
